name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://ayera.dl.sourceforge.net/project/miuiromports//Whyred/MASIK%20X/Masik%20X%2013.2%20v2%20Whyred%20port.zip
  ROM_NAME: MIUI:MasikX
  DYNAMIC_TYPE: OxygenOS
  ZIP_NAME: MasikX
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/JamieHoSzeYui/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ErfanGSIs
              sudo wget $ROM_URL
              mv *.zip fw.zip
              sudo ./dynamic.sh $DYNAMIC_TYPE fw.zip
              sudo ./make.sh out $ROM_NAME Aonly output
              sudo ./make.sh out $ROM_NAME AB output
       
       - name: Zip Aonly and upload 
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z          
       - name: Zip AB and upload 
         run: |
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              ./transfer bit ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z      
       - name: Upload build info
         run: |
              ./transfer bit ErfanGSIs/output/*-Aonly-*.txt
         
            
