name: Building GSI..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://oxygenos.oneplus.net/OnePlus7TProOxygen_14.O.17_OTA_017_all_2005192142_be17b4bb39484216.zip
  ROM_NAME: OxygenOS
  DYNAMIC_TYPE: OxygenOS
  ZIP_NAME: OOS
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget

       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/JamieHoSzeYui/ErfanGSIs
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ErfanGSIs
              sudo aria2c -x16 $ROM_URL
              mv *.zip fw.zip
              sudo ./dynamic.sh $DYNAMIC_TYPE fw.zip system
              mkdir final
              sudo ./make.sh system $ROM_NAME Aonly final
              sudo ./make.sh system $ROM_NAME AB final
       
       - name: Zip Aonly and upload 
         run: |
              cd ErfanGSIs/final
              zip -r $ZIP_NAME-GSI-Aonly.7z *-Aonly-*.img
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit $ZIP_NAME-GSI-Aonly.7z          
       - name: Zip AB and upload 
         run: |
              cd ErfanGSIs/final
              zip -r $ZIP_NAME-GSI-AB.7z *-AB-*.img
              ./transfer bit $ZIP_NAME-GSI-AB.7z      
       - name: Print build info
         run: |
              cd ErfanGSIs/final
              cat *-Aonly-.txt
         
            
